import { createSlice } from '@reduxjs/toolkit'

interface UserInfoI {
    id: number; // Optional for new users, as it seems to be autogenerated
    username: string;
    password: string;
    roleState: boolean;
    default: boolean;
    region: string;
    roleId: number;
    avatar: string;
    role: any
}
const initialState: UserInfoI | null = null
const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        setUserInfo: (state, action) => {
            state = action.payload
            return state
        },
        clearUserInfo: (state) => {
            state = null
            return state
        }
    }
})

export const { setUserInfo, clearUserInfo } = userSlice.actions;

export default userSlice.reducer;